export const Colors = {
    "default": "black",
     "gray": "gray",
     "brown": "brown",
     "orange": "orange",
     "yellow": "yellow",
     "green": "green",
     "blue": "blue",
     "purple": "purple",
     "pink": "pink",
     "red": "red",
     "gray_background": "gray",
     "brown_background": "brown",
     "orange_background": "orange",
     "yellow_background": "yellow",
     "green_background": "green",
     "blue_background": "blue",
     "purple_background": "purple",
     "pink_background": "pink",
     "red_background": "red",
}