import type { GetServerSidePropsContext, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Base } from '../../components/base'
import styles from '../../styles/Home.module.css'

const Page: NextPage<{data: any}> = ({data}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Page
        </h1>

        {data.results.map((resultElement: any, index: number) => {
          //i don't care about key now
          if(resultElement.type) {
            return <Base {...resultElement} key={index} />
          }
        })}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps = async (context: GetServerSidePropsContext) => {
  const {pageId} = context.query;
  const response = await fetch(`http://localhost:3000/api/hello/${pageId}`);
  const data = await response.json();
  return {
    props: {data}
  }
}
export default Page
